### ISSUE TITLE
[Bug]: ClassCastException when deserializing date column

### ISSUE THREAD

**Issue by qingfei1994** [itinycheng/flink-connector-clickhouse#151]
### What happened?

When I was running E2E test case reading a date column from clickhouse container, ClassCastException was thrown.
```[docker-java-stream-107643741] INFO  org.apache.flink.connector.clickhouse.FlinkContainerTestEnviroment - STDOUT: Caused by: java.lang.ClassCastException: class java.time.LocalDate cannot be cast to class java.sql.Date (java.time.LocalDate is in module java.base of loader 'bootstrap'; java.sql.Date is in module java.sql of loader 'platform')
[docker-java-stream-107643741] INFO  org.apache.flink.connector.clickhouse.FlinkContainerTestEnviroment - STDOUT:         at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseRowConverter.lambda$createToInternalConverter$f8d94b9$6(ClickHouseRowConverter.java:130)
[docker-java-stream-107643741] INFO  org.apache.flink.connector.clickhouse.FlinkContainerTestEnviroment - STDOUT:         at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseRowConverter.toInternal(ClickHouseRowConverter.java:83)
 [docker-java-stream-107643741] INFO  org.apache.flink.connector.clickhouse.FlinkContainerTestEnviroment - STDOUT:         at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchInputFormat.nextRecord(ClickHouseBatchInputFormat.java:135)
```

### Affects Versions

master

### How to reproduce

running E2E case(ClickhouseE2ECase.java) with date column.

```List<String> sqlLines = new ArrayList<>();
        sqlLines.add(
                "create table clickhouse_test (id int, name varchar,float32_column FLOAT,"
                        + "    date_column Date,\n"
                        + "    datetime_column TIMESTAMP(3),\n"
                        + "    array_column ARRAY<INT>) with ('connector' = 'clickhouse',\n"
                        + "  'url' = '"
                        + jdbcUrl
                        + "',\n"
                        + "  'table-name' = 'test',\n"
                        + "  'username'='test_username',\n"
                        + "  'password'='test_password'\n"
                        + ");");
        sqlLines.add(
                "create table test (id int, name varchar,float32_column FLOAT,\n"
                        + "date_column Date,\n"
                        + "    datetime_column TIMESTAMP(3),\n"
                        + "    array_column ARRAY<INT>) with ('connector' = 'clickhouse',\n"
                        + "  'url' = '"
                        + jdbcUrl
                        + "',\n"
                        + "  'table-name' = 'test_insert',\n"
                        + "  'username'='test_username',\n"
                        + "  'password'='test_password'\n"
                        + ");");
        sqlLines.add("insert into test select * from clickhouse_test;");
        submitSQLJob(
                sqlLines,
                SQL_CONNECTOR_CLICKHOUSE_JAR,
                CLICKHOUSE_JDBC_JAR,
                HTTPCORE_JAR,
                HTTPCLIENT_JAR,
                HTTPCLIENT_H2_JAR);
```

### Anything else

I've figured out how to fix it. 
In ClickHouseRowConverter.java
` case DATE:
                return val -> (int) ((Date) val).toLocalDate().toEpochDay();`

changed into

`case DATE:
                return val -> (int) ((LocalDate)val).toEpochDay();`

As val is already LocalDate type,  no need to cast it to java.sql.Date.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qingfei1994** [comment]
I just found out #145 already fix the issue. Will supplement a test case for date column then.
