### ISSUE TITLE
[Bug]: cluster空指针

### ISSUE THREAD

**Issue by jackj-ohn1** [itinycheng/flink-connector-clickhouse#152]
### What happened?

连接ClickHouse集群上的某个节点后，执行基本的查询操作报错。

### Affects Versions

commit：279b6ac6dc

### What are you seeing the problem on?

Flink-Table-Api (SQL)

### Relevant log output

```shell
Caused by: java.lang.NullPointerException
	at org.apache.flink.connector.clickhouse.util.ClickHouseJdbcUtil.getDistributedEngineFull(ClickHouseJdbcUtil.java:70)
	at org.apache.flink.connector.clickhouse.internal.AbstractClickHouseInputFormat$Builder.build(AbstractClickHouseInputFormat.java:208)
进入查看后发现是：
 String engineFull = rs.getString("engine_full").replaceAll("'|\\s", "");
                    Matcher matcher = DISTRIBUTED_TABLE_ENGINE_PATTERN.matcher(engineFull);
                    String cluster;
                    if (matcher.find()) {
                        cluster = matcher.group("cluster");
                        String database = matcher.group("database");
                        String table = matcher.group("table");
                        String shardingKey = matcher.group("shardingKey");
                        DistributedEngineFull var13 = DistributedEngineFull.of(cluster, database, table, ClickHouseUtil.parseShardingKey(shardingKey), (String)null);
                        return var13;
                    }

                    cluster = null;
                    return cluster;这里的cluster被赋值为null，但手动执行查询语句获得的结果是没有问题的SELECT engine_full FROM system.tables WHERE database = ? AND name = ?
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by qingfei1994** [comment]
试一下用最新的master分支跑一遍？
如果还是不行，发一下`SELECT engine_full FROM system.tables WHERE database = ? AND name = ?`的输出结果

**Comment by itinycheng** [comment]
@jackj-ohn1 

报错说是第70行空指针，看下是不是url配置的问题，connection为空导致的，代码截图：
![image](https://github.com/user-attachments/assets/30e1085a-3540-4db1-ba5a-2dad22336221)

**Comment by czy006** [comment]
cc @qingfei1994

**Comment by lucklymore** [comment]
> @jackj-ohn1
> 
> 报错说是第70行空指针，看下是不是url配置的问题，connection为空导致的，代码截图： ![image](https://private-user-images.githubusercontent.com/14097070/361631117-30e1085a-3540-4db1-ba5a-2dad22336221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTQzNDIsIm5iZiI6MTczMzU1NDA0MiwicGF0aCI6Ii8xNDA5NzA3MC8zNjE2MzExMTctMzBlMTA4NWEtMzU0MC00ZGIxLWJhNWEtMmRhZDIyMzM2MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA2NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YTA4MDZlMzEzMjIwNTk4NmJjMDM3N2UxMDM2MzAyMDQ1MGIzMzE4Y2EyNDgxY2ZmMWU3OWNmMzg2OTdiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nnZyBrQu1mQbLpYEjykJ80qymh2kbtd9urmXBoT8BVo)

@itinycheng 大佬，master分支下，这里url地址必须是完整得jdbc:clickhouse://x.x.x.x:8123地址，前头必须带jdbc，否则会导致url地址判断错误，返回connetion为空，导致报错
另外尝试jdbc:clickhouse://host1:8123,host2:8123,host3:8123集群模式，实际上也只创建了与第一个host地址得连接，未使用多个连接串，请求也只往第一个发

**Comment by itinycheng** [comment]
> > @jackj-ohn1
> > 报错说是第70行空指针，看下是不是url配置的问题，connection为空导致的，代码截图： ![image](https://private-user-images.githubusercontent.com/14097070/361631117-30e1085a-3540-4db1-ba5a-2dad22336221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTQzNDIsIm5iZiI6MTczMzU1NDA0MiwicGF0aCI6Ii8xNDA5NzA3MC8zNjE2MzExMTctMzBlMTA4NWEtMzU0MC00ZGIxLWJhNWEtMmRhZDIyMzM2MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA2NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YTA4MDZlMzEzMjIwNTk4NmJjMDM3N2UxMDM2MzAyMDQ1MGIzMzE4Y2EyNDgxY2ZmMWU3OWNmMzg2OTdiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nnZyBrQu1mQbLpYEjykJ80qymh2kbtd9urmXBoT8BVo)
> 
> @itinycheng 大佬，master分支下，这里url地址必须是完整得jdbc:clickhouse://x.x.x.x:8123地址，前头必须带jdbc，否则会导致url地址判断错误，返回connetion为空，导致报错 另外尝试jdbc:clickhouse://host1:8123,host2:8123,host3:8123集群模式，实际上也只创建了与第一个host地址得连接，未使用多个连接串，请求也只往第一个发

@lucklymore Master分支改Url pattern了，flink option配置的url会直接传递给`clickhouse-jdbc`，配置多个host本应该是随机连一个的available的，这样有一定容错性吧；Master的readme等一些地方还没修改，最近一直没时间管；

**Comment by lucklymore** [comment]
> > > @jackj-ohn1
> > > 报错说是第70行空指针，看下是不是url配置的问题，connection为空导致的，代码截图： ![image](https://private-user-images.githubusercontent.com/14097070/361631117-30e1085a-3540-4db1-ba5a-2dad22336221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NTQzNDIsIm5iZiI6MTczMzU1NDA0MiwicGF0aCI6Ii8xNDA5NzA3MC8zNjE2MzExMTctMzBlMTA4NWEtMzU0MC00ZGIxLWJhNWEtMmRhZDIyMzM2MjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDA2NDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3YTA4MDZlMzEzMjIwNTk4NmJjMDM3N2UxMDM2MzAyMDQ1MGIzMzE4Y2EyNDgxY2ZmMWU3OWNmMzg2OTdiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nnZyBrQu1mQbLpYEjykJ80qymh2kbtd9urmXBoT8BVo)
> > 
> > 
> > @itinycheng 大佬，master分支下，这里url地址必须是完整得jdbc:clickhouse://x.x.x.x:8123地址，前头必须带jdbc，否则会导致url地址判断错误，返回connetion为空，导致报错 另外尝试jdbc:clickhouse://host1:8123,host2:8123,host3:8123集群模式，实际上也只创建了与第一个host地址得连接，未使用多个连接串，请求也只往第一个发
> 
> @lucklymore Master分支改Url pattern了，flink option配置的url会直接传递给`clickhouse-jdbc`，配置多个host应该是随机连一个available的，这样有一定容错性吧；Master的readme等一些地方还没修改，最近一直没时间管；

@itinycheng 好的大佬，我多翻翻代码，配置多个host应该是随机连一个available的，这个有一定容错性，但是负载均衡这块目前达不到，flink转发请求只有一个机器，吞吐有限，翻了下clickhouse java jdbc项目，看了下部分loadbalance的issue，url可以传入clickhouse jdbc参数，auto_discovery；load_balancing_policy 在尝试这部分参数的效果
