### ISSUE TITLE
org.apache.flink.connector.clickhouse.internal.executor.ClickHouseExecutor  - ClickHouse executeBatch error

### ISSUE THREAD

**Issue by Princewjh** [itinycheng/flink-connector-clickhouse#31]
执行upsert 模式 报错，具体信息如下：
160123 [clickhouse-batch-output-format-thread-1] ERROR org.apache.flink.connector.clickhouse.internal.executor.ClickHouseExecutor  - ClickHouse executeBatch error, retry times = 0
java.sql.SQLSyntaxErrorException: Query must be like 'INSERT INTO [db.]table [(c1, c2, c3)] VALUES (?, ?, ?)'. Got: ALTER TABLE `default`.`order` UPDATE `userName`=?, `orderID`=? WHERE `orderName`=?
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:327)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:320)
	at org.apache.flink.connector.clickhouse.internal.executor.ClickHouseExecutor.attemptExecuteBatch(ClickHouseExecutor.java:53)
	at org.apache.flink.connector.clickhouse.internal.executor.ClickHouseUpsertExecutor.executeBatch(ClickHouseUpsertExecutor.java:125)
	at org.apache.flink.connector.clickhouse.internal.AbstractClickHouseOutputFormat.checkBeforeFlush(AbstractClickHouseOutputFormat.java:74)
	at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat.flush(ClickHouseBatchOutputFormat.java:93)
	at org.apache.flink.connector.clickhouse.internal.AbstractClickHouseOutputFormat.lambda$scheduledFlush$0(AbstractClickHouseOutputFormat.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

代码如下：
![image](https://user-images.githubusercontent.com/29514357/170161153-34a42878-24fb-41ab-9be9-b1b83bc7060c.png)

**Comment by itinycheng** [comment]
Hi, This exception is caused by version conflict, there should be a `0.3.0` or earlier version of ClickHouse JDBC dependency in your project, upgrade the version to 0.3.1 and test it.

![image](https://user-images.githubusercontent.com/14097070/170276553-68dbb37c-3988-4f3f-bacb-8d11a5932694.png)
