### ISSUE TITLE
sink.ignore-delete

### ISSUE THREAD

**Issue by dulangMaster** [itinycheng/flink-connector-clickhouse#7]
sink.ignore-delete =false
issues java.lang.UnsupportedOperationException: Please use `prepareStatement(ClickHouseConnection connection)` instead.
	at org.apache.flink.connector.clickhouse.internal.executor.ClickHouseUpsertExecutor.prepareStatement(ClickHouseUpsertExecutor.java:63)
	at org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat.open(ClickHouseBatchOutputFormat.java:63)
	... 13 more

**Comment by itinycheng** [comment]
Thank you for reporting the issue.
This is a bug, I will fix it as soon as possible.

**Comment by itinycheng** [comment]
https://github.com/itinycheng/flink-connector-clickhouse/commit/4ef0612f42e4826a096307d24c026c43f84ba1d4
Bug fixed, but I don’t really recommend using this feature.
Please do enough tests before you decide to use this feature.
