### ISSUE TITLE
服务器运行找不到clickhouse连接器

### ISSUE THREAD

**Issue by limingoo** [itinycheng/flink-connector-clickhouse#80]
Caused by: org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'clickhouse' that implements 'org.apache.flink.table.factories.DynamicTableFactory' in the classpath.

Available factory identifiers are:

blackhole
datagen
filesystem
kafka
print
upsert-kafka
        at org.apache.flink.table.factories.FactoryUtil.discoverFactory(FactoryUtil.java:545) ~[flink-table-api-java-uber-1.16.0.jar:1.16.0]
        at org.apache.flink.table.factories.FactoryUtil.enrichNoMatchingConnectorError(FactoryUtil.java:731) ~[flink-table-api-java-uber-1.16.0.jar:1.16.0]
        at org.apache.flink.table.factories.FactoryUtil.discoverTableFactory(FactoryUtil.java:709) ~[flink-table-api-java-uber-1.16.0.jar:1.16.0]
        at org.apach

**Comment by xishuaidelin** [comment]
hello, I have also encountered this problem. May I ask how you solved it?
