### ISSUE TITLE
报错，flink 集群运行找不到类org.apache.flink.shaded.clickhouse.org.apache.commons.logging.impl.LogFactoryImpl

### ISSUE THREAD

**Issue by limingoo** [itinycheng/flink-connector-clickhouse#81]
Caused by: java.lang.IllegalStateException: cannot initialize http client
        at org.apache.flink.shaded.clickhouse.ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:76)
        at org.apache.flink.shaded.clickhouse.ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:62)
        at org.apache.flink.shaded.clickhouse.ru.yandex.clickhouse.BalancedClickhouseDataSource.getConnection(BalancedClickhouseDataSource.java:195)
        at org.apache.flink.connector.clickhouse.internal.connection.ClickHouseConnectionProvider.createConnection(ClickHouseConnectionProvider.java:123)
        at org.apache.flink.connector.clickhouse.internal.connection.ClickHouseConnectionProvider.getOrCreateConnection(ClickHouseConnectionProvider.java:61)
        at org.apache.flink.connector.clickhouse.internal.AbstractClickHouseOutputFormat$Builder.build(AbstractClickHouseOutputFormat.java:196)
        ... 37 more
Caused by: org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: org.apache.flink.shaded.clickhouse.org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: org.apache.flink.shaded.clickhouse.org.apache.commons.logging.impl.LogFactoryImpl)
        at org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
        at org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
        at org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
        at org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
        at org.apache.flink.shaded.clickhouse.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.<init>(DefaultHttpClientConnectionOperator.java:69)
        at org.apache.flink.shaded.clickhouse.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:165)
        at org.apache.flink.shaded.clickhouse.ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.getConnectionManager(ClickHouseHttpClientBuilder.java:150)
        at org.apache.flink.shaded.clickhouse.ru.yandex.clickhouse.util.ClickHouseHttpClientBuilder.buildClient(ClickHouseHttpClientBuilder.java:73)
        at org.apache.flink.shaded.clickhouse.ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:74)
        ... 42 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.shaded.clickhouse.org.apache.commons.logging.impl.LogFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:67)
        at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:65)
        at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:51)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.flink.shaded.clickhouse.org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)

**Comment by itinycheng** [comment]
@limingoo 
Maybe it's related to the maven version, Use the command: `./mvnw clean package -DskipTests`
