### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat

### ISSUE THREAD

**Issue by Achilles1996** [itinycheng/flink-connector-clickhouse#96]
编译master 使用flinksql 提交任务 报错

**Comment by Achilles1996** [comment]
WITH (
  	 'connector' = 'clickhouse',
      'url' = 'clickhouse://192.168.12.34:8123',
      'database-name' = 'mysql_JM',
      'table-name' = 't_bp_salepos_d',
  	 'username' = 'default',
  	 'password' = 'CK@123'
  );

**Comment by itinycheng** [comment]
任务没加载到connector的jar吧，flink/lib下没放connector或是用错包了(用饱含dependencies的jar)？

**Comment by Achilles1996** [comment]
加载到connector的jar了，因为在flinksql的client中使用CREATE CATALOG clickhouse了可以查询到有那些数据库，那些表；
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/51429792/334ce3ce-3415-42f5-b916-e1796b625724)

我是flink1.16.2的版本，使用了flinksql的方式提交任务，standlone的模式， 
![image](https://github.com/itinycheng/flink-connector-clickhouse/assets/51429792/3fddcf74-7518-492d-b495-2e52627b495f)

呜呜

**Comment by itinycheng** [comment]
@Achilles1996 
如果`create ClickHouse Catalog` 正常可用说明确实已经加载到jar了；
`ClassNotFoundException`也可能是加载ClickHouseBatchOutputFormat类失败，具体原因还是多看看sql client log吧；
根据以上信息我定位不到具体原因；

**Comment by zenoprod** [comment]
这个是报错日志，可以麻烦看看是什么问题嘛
[log.txt](https://github.com/itinycheng/flink-connector-clickhouse/files/13276633/log.txt)



> @Achilles1996 如果`create ClickHouse Catalog` 正常可用说明确实已经加载到jar了； `ClassNotFoundException`也可能是加载ClickHouseBatchOutputFormat类失败，具体原因还是多看看sql client log吧； 根据以上信息我定位不到具体原因；

**Comment by wolfewf** [comment]
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:300)
	at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.<init>(InputOutputFormatContainer.java:66)
	... 18 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003)
	我这边报了这个错误 @itinycheng 这个有解决吗

**Comment by limingoo** [comment]
遇到了同样的问题，我使用的是1.16.0版本，在使用flink sql过程中遇到java.lang.ClassNotFoundException: org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat异常，可以查询到表，但是不能读取数据

**Comment by limingoo** [comment]
> Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:300) at org.apache.flink.runtime.jobgraph.InputOutputFormatContainer.(InputOutputFormatContainer.java:66) ... 18 more Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.clickhouse.internal.ClickHouseBatchOutputFormat at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527) at java.base/java.lang.Class.forName0(Native Method) at java.base/java.lang.Class.forName(Class.java:398) at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78) at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2003) 我这边报了这个错误 @itinycheng 这个有解决吗

别用select * ；
